### ISSUE TITLE
extract navigation into separate project?

### ISSUE THREAD

**Issue by markokocic** [flexsurfer/rn-shadow-steroid#2]
`rn-shadow-steroid` works great for its primary purpose of seamlessly wrapping `react-native` components and providing a support for hot-reloading while developing using `shadow-cljs`. The base is simple and works great with the pure reagent. I can see it as a dependency for every Clojurescript react-native project.

However, the `react-navigation` support adds additional functionality on top of that, and pulls additional dependencies, like `re-frame`. This makes the project more opinionated regarding the tech stack, and this part can as well justify itself to be a separate library.

Are there any plans to split this project into the small core, and separate project for navigation, or it's going to be kept as is?

Or, in case of "all in one" approach, are there some plans to add more wrappers for react native components, for example for `native-base` or `react-native-elements`?

**Comment by flexsurfer** [comment]
hi! thanks for your feedback, I was thinking about that and decided to go with monorepo, because shadow cljs works really great with dependencies and if you don't use navigation it doesn't care about re-frame, but still this library mostly for apps which uses re-frame

about wrappers please file an issue with components you need and I'll add them, thanks!

**Comment by markokocic** [comment]
When opening a ticket I was thinking about adding support for `native-base` component library, Meanwhile I created a separate wrapper [here](/markokocic/rn-native-base) and an [example](/markokocic/rn-native-base-example-todo).

I see `rn-shadow-steroid`  library as a starting point to jumpstart my Clojurescript react-native based projects, and then include separate dependencies only if needed.

I can agree that react-navigation and a minimal set of curated component belongs here.

Other libraries can be also added easily, but it would lead to the bloat of the project.
