### ISSUE TITLE
Picker component deprecation

### ISSUE THREAD

**Issue by markokocic** [flexsurfer/rn-shadow-steroid#3]
When running the react-native application with the latest react-native version I get the deprecation warning that the Picker is now deprecated in react-native, and will be removed in the next release.

Instead, one should switch to the `@react-native-community/picker` component. 

More info at the new [picker project page](/react-native-community/react-native-picker)

The picker component should either be removed from the steroid.rn.core namespace or kept there, but use the new implementation instead.

**Comment by flexsurfer** [comment]
thanks, i'll take a look!

**Comment by flexsurfer** [comment]
0.2.1
