### ISSUE TITLE
Add wrappers for additional react-native libraries

### ISSUE THREAD

**Issue by markokocic** [flexsurfer/rn-shadow-steroid#4]
As discussed in #2 and #3 please add wrappers for the following common components. Ideally they should reside in separate namespace, and don't influence the build if not required.

- https://github.com/react-native-community/async-storage
- https://github.com/react-native-community/react-native-picker - mentioned in #3 
- https://github.com/react-native-community/datetimepicker
- https://github.com/oblador/react-native-vector-icons - with support for various icon sets

**Comment by flexsurfer** [comment]
0.2.1
